"""
Seed URL collection for Kurdish websites.
This module contains known Kurdish websites gathered from directories,
media lists, Wikipedia lists, and other public sources.
"""

# =============================================================================
# KNOWN KURDISH NEWS AND MEDIA WEBSITES
# =============================================================================
KNOWN_KURDISH_NEWS = [
    # Major Kurdish news agencies and outlets
    "https://www.rudaw.net",
    "https://www.kurdistan24.net",
    "https://www.nrttv.com",
    "https://www.kirkuknow.com",
    "https://www.basnews.com",
    "https://www.shafaq.com",
    "https://www.xendan.org",
    "https://www.awene.com",
    "https://www.hawlati.co",
    "https://www.peyamner.com",
    "https://www.pukmedia.com",
    "https://www.gulan-media.com",
    "https://www.smartnews.agency",
    "https://www.kurdpress.com",
    "https://www.dengiamerica.com",
    "https://www.yek-dem.com",
    "https://www.ronahi.tv",
    "https://www.hawar.news",
    "https://www.hawarnews.com",
    "https://www.rojavanews.com",
    "https://www.anfenglish.com",
    "https://www.anfkurdi.com",
    "https://www.anfarabic.com",
    "https://www.kurdistanpress.com",
    "https://www.kurdistan-post.eu",
    "https://www.ekurd.net",
    "https://www.kurdistantribune.com",
    "https://www.kurdishglobe.net",
    "https://www.kurdishinfo.com",
    "https://www.firatajans.com",
    "https://www.firatnews.com",
    "https://www.jiyanpress.com",
    "https://www.rozhnamavan.com",
    "https://www.kurdiu.org",
    "https://www.peshmergekan.com",
    "https://www.kurdistan.ru",
    "https://www.kdp.info",
    "https://www.puk.org",
    "https://www.gorran.net",
    "https://www.islamicpartyofkurdistan.com",
    "https://www.yekgirtu.org",
    "https://www.komal.org",
    "https://www.nfrtkurdistan.com",
    "https://www.kdsp.org",
    "https://www.azadiyawelat.com",
    "https://www.wlatey.me",
    "https://www.sharpress.net",
    "https://www.knnc.net",
    "https://www.payam.tv",
    "https://www.gelawej.net",
    "https://www.bianet.org",
    "https://www.mezopotamyaajansi.com",
    "https://www.rojakurdistan.com",
    "https://www.kurdistannews.net",
    "https://www.kurdmedia.com",
    "https://www.dengikurdistan.net",
    "https://www.radiokurdistan.net",
    "https://www.dengikurdistan.com",
    "https://www.voakurdish.com",
    "https://www.bbcarabi.com",
    "https://www.bbckurdi.com",
    "https://www.bbc.com/kurdish",
    "https://www.bbc.com/persian",
    "https://www.alhurra.com",
    "https://www.iraqhurr.org",
    "https://www.radiofarda.com",
    "https://www.dw.com/ku",
    "https://www.dw.com/ckb",
    "https://www.france24.com/ku",
    "https://www.trtworld.com",
    "https://www.trtarabi.com",
    "https://www.trtkurdi.com.tr",
    "https://www.roj.tv",
    "https://www.sterk.tv",
    "https://www.medyanews.com",
    "https://www.nuceciwan115.xyz",
    "https://www.nuceciwan.info",
    "https://www.rohanipress.com",
    "https://www.evinkurd.com",
    "https://www.cfrmedia.com",
    "https://www.pdk-iran.org",
    "https://www.pdki.org",
    "https://www.komelakurdistan.org",
    "https://www.komala.org",
    "https://www.pjak.org",
    "https://www.rojhelat.info",
    "https://www.rojhilat.info",
    "https://www.enks.info",
    "https://www.smekurdistan.net",
    "https://www.tevdem.org",
    "https://www.hawpshti.com",
    "https://www.warvin.org",
    "https://www.ruwange.com",
    "https://www.kurd1.tv",
    "https://www.zagrosmedia.com",
    "https://www.zagrostv.com",
    "https://www.kurdmax.tv",
    "https://www.kurdsat.tv",
    "https://www.koreksat.tv",
    "https://www.gali-kurdistan.com",
    "https://www.nawandnews.com",
    "https://www.kurdnews.com",
    "https://www.khamapress.com",
    "https://www.iraqinews.com",
    "https://www.alsumaria.tv",
    "https://www.almadapress.com",
]

# =============================================================================
# KURDISH CULTURAL, EDUCATIONAL, AND REFERENCE SITES
# =============================================================================
KNOWN_KURDISH_CULTURAL = [
    "https://www.kurdishacademy.org",
    "https://www.institutkurde.org",
    "https://www.kurdipedia.org",
    "https://www.pertukal.com",
    "https://www.amude.net",
    "https://www.kurdistanica.com",
    "https://www.kurdish-academy.org",
    "https://www.weqfa-kurdi.org",
    "https://www.bnk.gov.krd",
    "https://www.ckb.wikipedia.org",
    "https://ckb.wikipedia.org",
    "https://ku.wikipedia.org",
    "https://ku.wiktionary.org",
    "https://ckb.wiktionary.org",
    "https://www.ferheng.org",
    "https://www.ferheng.com",
    "https://www.dictio.kurdi.com",
    "https://www.kurdi.com",
    "https://www.kurd.cc",
    "https://www.kurdblogger.com",
    "https://www.kurdishlyrics.com",
    "https://www.kurdishmusic.eu",
    "https://www.lutkurdistan.com",
    "https://www.duhokheritage.com",
    "https://www.kurdishcinema.com",
    "https://www.kurdishfilm.com",
    "https://www.kurditgroup.org",
    "https://www.krmanj.org",
    "https://www.ezidikhan.com",
    "https://www.lalish.info",
    "https://www.yezidi.org",
    "https://www.yezidipost.com",
    "https://www.ezidikan.com",
    "https://www.yarsanism.com",
    "https://www.kakayi.com",
    "https://www.feylikurds.com",
    "https://www.faili.net",
    "https://www.gorani.org",
    "https://www.hawrami.com",
    "https://www.zazaki.net",
    "https://www.zazapress.com",
    "https://www.dimli.info",
    "https://www.tonbakurd.com",
    "https://www.sardam.info",
    "https://www.zhinkurd.com",
    "https://www.amako.info",
    "https://www.welatparez.com",
    "https://www.azadliq.org",
    "https://www.zivmagazine.com",
    "https://www.evro.krd",
    "https://www.kurdistanmemory.com",
    "https://www.zhiannews.com",
    "https://www.kurd.org",
    "https://www.hfrk.org",
    "https://www.kurdishculture.com",
    "https://www.kurdishheritage.org",
    "https://www.kurdishproject.org",
    "https://www.kurdishstudies.net",
    "https://www.kurdishcentre.com",
    "https://www.washington.edu/kirsi",
    "https://www.kurdishlobby.com",
    "https://www.kurdishrights.org",
    "https://www.unpo.org",
    "https://www.khrp.org",
    "https://www.kurdistanhumanrights.org",
    "https://www.kurdistancommentary.com",
    "https://www.thekurdishproject.org",
    "https://www.kurdistanmedia.com",
    "https://www.kurdcoin.org",
    "https://www.zheen.com",
    "https://www.regaonline.com",
]

# =============================================================================
# KURDISH GOVERNMENT AND INSTITUTIONAL SITES
# =============================================================================
KNOWN_KURDISH_GOVERNMENT = [
    "https://gov.krd",
    "https://www.gov.krd",
    "https://www.krg.org",
    "https://www.mhe.krg.org",
    "https://www.krp.org",
    "https://www.parliament.krd",
    "https://www.presidency.krd",
    "https://www.cabinet.gov.krd",
    "https://www.mof.gov.krd",
    "https://www.moe-krg.com",
    "https://www.mofa.gov.krd",
    "https://www.moi.gov.krd",
    "https://www.moj.gov.krd",
    "https://www.krso.gov.krd",
    "https://www.krp.gov.krd",
    "https://www.kck-info.com",
    "https://www.hpg-online.com",
    "https://www.pkkonline.com",
    "https://www.kongrakurdistan.net",
    "https://www.ypgrojava.org",
    "https://www.sdf-press.com",
    "https://www.afrinkanton.com",
    "https://www.aa.com.tr",
    "https://www.dfns.net",
    "https://www.hawlergov.org",
    "https://www.sfrk.info",
    "https://www.gorannews.net",
    "https://www.kurd.store",
    "https://www.mnr.krg.org",
]

# =============================================================================
# KURDISH TECHNOLOGY AND SOCIAL MEDIA SITES
# =============================================================================
KNOWN_KURDISH_TECH = [
    "https://www.kurddev.com",
    "https://www.kurdtechno.com",
    "https://www.kurd.io",
    "https://www.kurdchat.com",
    "https://www.kurdtelegram.com",
    "https://www.tishk.tv",
    "https://www.speda.tv",
    "https://www.gksat.tv",
    "https://www.kurdtvs.com",
    "https://www.kurdchannel.tv",
    "https://www.jwanpress.com",
    "https://www.khakpress.com",
    "https://www.aweza.net",
    "https://www.kurdpress.ir",
    "https://www.iknews.com",
    "https://www.kurdistanmedia.net",
    "https://www.saradistribution.com",
    "https://www.chaknews.com",
    "https://www.aknews.com",
    "https://www.akhbar.com",
]

# =============================================================================
# KURDISH E-COMMERCE AND BUSINESS
# =============================================================================
KNOWN_KURDISH_BUSINESS = [
    "https://www.kurdishstore.com",
    "https://www.slemani.com",
    "https://www.erbilcitadel.org",
    "https://www.erbillifestyle.com",
    "https://www.sulaymaniyah.com",
    "https://www.duhok.org",
    "https://www.kirkuk.us",
    "https://www.hawler.info",
    "https://www.kurdistanshop.com",
    "https://www.bazarekurd.com",
]

# =============================================================================
# KURDISH HEALTH AND EDUCATION
# =============================================================================
KNOWN_KURDISH_EDUCATION = [
    "https://www.uos.edu.krd",
    "https://www.su.edu.krd",
    "https://www.hmu.edu.krd",
    "https://www.uod.ac",
    "https://www.epu.edu.iq",
    "https://www.uhd.edu.iq",
    "https://www.auis.edu.krd",
    "https://www.cihanuniversity.edu.iq",
    "https://www.koyauniversity.org",
    "https://www.uor.edu.krd",
    "https://www.tiu.edu.iq",
    "https://www.lfu.edu.krd",
    "https://www.ukh.edu.krd",
    "https://www.ishik.edu.iq",
    "https://www.charmo.edu.krd",
    "https://www.halabjauni.edu.krd",
    "https://www.garmian.edu.krd",
    "https://www.su.edu.iq",
    "https://www.raperin.edu.krd",
    "https://www.komar.edu.iq",
    "https://www.bnu.edu.iq",
    "https://www.knowledge.edu.krd",
    "https://www.cihan.edu.iq",
    "https://www.moi.gov.krd",
    "https://www.health.gov.krd",
    "https://www.mnr.gov.krd",
    "https://www.mop.gov.krd",
    "https://www.mot.gov.krd",
    "https://www.mol.gov.krd",
    "https://www.mohe.gov.krd",
    "https://www.moe.gov.krd",
]

# =============================================================================
# KURDISH SPORTS AND ENTERTAINMENT
# =============================================================================
KNOWN_KURDISH_SPORTS = [
    "https://www.kurdistansport.com",
    "https://www.varzkurdistan.com",
    "https://www.kurdsport.net",
    "https://www.sportskurd.com",
    "https://www.sportnews.krd",
    "https://www.kurdgame.com",
    "https://www.kurdcinema.com",
    "https://www.kurdfilms.com",
    "https://www.kurdrama.com",
    "https://www.erbilmarathon.com",
]

# =============================================================================
# DIASPORA AND INTERNATIONAL KURDISH SITES
# =============================================================================
KNOWN_KURDISH_DIASPORA = [
    "https://www.kurdistan.co.uk",
    "https://www.kurdistan-report.de",
    "https://www.kurdishmedia.com",
    "https://www.kurdishquestion.com",
    "https://www.kurdistan-report.com",
    "https://www.kurdishinstitute.be",
    "https://www.kurdistan-parliament.eu",
    "https://www.navkurd.de",
    "https://www.fek-online.com",
    "https://www.amara-kurd.com",
    "https://www.kurdistanweekly.com",
    "https://www.komkarxorasan.org",
    "https://www.yxkonline.com",
    "https://www.kurdistan.nl",
    "https://www.kurdistan.se",
    "https://www.kurdistanforum.de",
    "https://www.kurdwatch.org",
    "https://www.civaka-azad.org",
    "https://www.pydrojava.com",
    "https://www.ronahi.net",
    "https://www.amed.to",
    "https://www.efrin.net",
    "https://www.kobane.com",
    "https://www.kurdistanamericalatina.org",
    "https://www.kurdishinstitute.org",
    "https://www.kurdistanfirst.com",
    "https://www.kurdistanica.com",
    "https://www.kurdistan-report.net",
    "https://www.navenda-nuceyan.com",
    "https://www.kurdistan-solidaritaet.de",
    "https://www.kurdishnews.com",
    "https://www.kurdishjournalists.com",
    "https://www.demokratischekraefte.com",
    "https://www.kurdistancenter.com",
    "https://www.kurdistangeneration.com",
    "https://www.diakurdistan.com",
]

# =============================================================================
# ADDITIONAL KURDISH BLOGS AND FORUMS
# =============================================================================
KNOWN_KURDISH_BLOGS = [
    "https://www.kurdblogger.com",
    "https://www.kurdforum.com",
    "https://www.kurdistan-forum.com",
    "https://www.kurdophone.com",
    "https://www.kurdnet.com",
    "https://www.penase.com",
    "https://www.penus.krd",
    "https://www.binav.com",
    "https://www.zardalyan.com",
    "https://www.zanist.org",
    "https://www.speemedia.com",
    "https://www.newrozpost.com",
    "https://www.zhiannews.com",
    "https://www.newroz.com",
    "https://www.azadikurd.com",
    "https://www.kurdishautonomyinformation.com",
    "https://www.kurdishstruggle.com",
    "https://www.hevallo.com",
    "https://www.kurdishdailynews.com",
    "https://www.thekurdisharena.com",
    "https://www.kurdishwomanpost.com",
    "https://www.womeninwar.org",
    "https://www.jinnews.com.tr",
    "https://www.jinhaagency.com",
    "https://www.jinlife.com",
    "https://www.zankoline.com",
    "https://www.kurdishbooks.com",
    "https://www.kanipedia.org",
    "https://www.nefel.com",
    "https://www.xelk.org",
    "https://www.payamnwe.com",
    "https://www.rizgarinews.com",
    "https://www.aramnews.com",
    "https://www.livancn.com",
    "https://www.dangiiran.com",
    "https://www.danginwe.com",
    "https://www.malpera.net",
    "https://www.ciwannews.com",
    "https://www.peykurdistan.com",
]

# =============================================================================
# RELIGIOUS KURDISH SITES
# =============================================================================
KNOWN_KURDISH_RELIGIOUS = [
    "https://www.difraq.com",
    "https://www.islamkurd.com",
    "https://www.ehlibeyt.info",
    "https://www.qurankurdi.com",
    "https://www.azadikurdistan.com",
    "https://www.lalish.org",
    "https://www.yezidism.com",
    "https://www.shareyezidi.com",
    "https://www.ezidpress.com",
    "https://www.kaniyanews.com",
    "https://www.dengeyezidi.com",
    "https://www.xudanews.com",
    "https://www.shingalmedia.com",
    "https://www.christiankurdistan.com",
    "https://www.chaldean.org",
    "https://www.ankawa.com",
]


def get_all_seed_urls():
    """Return all seed URLs from all categories."""
    all_urls = []
    all_urls.extend(KNOWN_KURDISH_NEWS)
    all_urls.extend(KNOWN_KURDISH_CULTURAL)
    all_urls.extend(KNOWN_KURDISH_GOVERNMENT)
    all_urls.extend(KNOWN_KURDISH_TECH)
    all_urls.extend(KNOWN_KURDISH_BUSINESS)
    all_urls.extend(KNOWN_KURDISH_EDUCATION)
    all_urls.extend(KNOWN_KURDISH_SPORTS)
    all_urls.extend(KNOWN_KURDISH_DIASPORA)
    all_urls.extend(KNOWN_KURDISH_BLOGS)
    all_urls.extend(KNOWN_KURDISH_RELIGIOUS)
    return list(set(all_urls))


CATEGORY_MAP = {
    "news": KNOWN_KURDISH_NEWS,
    "cultural": KNOWN_KURDISH_CULTURAL,
    "government": KNOWN_KURDISH_GOVERNMENT,
    "tech": KNOWN_KURDISH_TECH,
    "business": KNOWN_KURDISH_BUSINESS,
    "education": KNOWN_KURDISH_EDUCATION,
    "sports": KNOWN_KURDISH_SPORTS,
    "diaspora": KNOWN_KURDISH_DIASPORA,
    "blogs": KNOWN_KURDISH_BLOGS,
    "religious": KNOWN_KURDISH_RELIGIOUS,
}

if __name__ == "__main__":
    urls = get_all_seed_urls()
    print(f"Total unique seed URLs: {len(urls)}")
    for cat, lst in CATEGORY_MAP.items():
        print(f"  {cat}: {len(lst)}")
